---
- name: Install | Add jetson-clocks.conf
  copy:
    src: jetson_clocks.conf
    dest: /etc/
    mode: 0644

- name: Install | Add jetson-clocks.service
  copy:
    src: jetson-clocks.service
    dest: /lib/systemd/system/
    mode: 0644

- name: Config | Config systemd enable jetson-clocks.service
  systemd:
    name: jetson-clocks.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Config | Disable zram config
  systemd:
    name: nvzramconfig.service
    enabled: no
    state: stopped
