---
- name: Install | Add jetson-clocks.conf
  copy:
    src: jetson_clocks.conf
    dest: /etc/
    mode: 0644

- name: Install | Add jetson-clocks.service
  copy:
    src: jetson-clocks.service
    dest: /lib/systemd/system/
    mode: 0644

- name: Config | Config systemd enable jetson-clocks.service
  systemd:
    name: jetson-clocks.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Config | Disable zram config
  systemd:
    name: nvzramconfig.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Config | Disable zram config
  systemd:
    name: zram-config.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: CNI | make sure /opt/cni/bin exists
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download | Download CNI plugins
  get_url:
    url: "{{ cni_plugin_url }}"
    dest: "/tmp/cni-plugins-linux-{{ cni_plugin_arch }}-{{ cni_plugin_version }}.tgz"
    mode: '0440'
  retries: 4

- name: CNI | Install CNI plugins
  unarchive:
    src: "/tmp/cni-plugins-linux-{{ cni_plugin_arch }}-{{ cni_plugin_version }}.tgz"
    dest: "/opt/cni/bin"
    mode: 0755
    remote_src: yes
