---
- name: Config | Get current username
  command: whoami
  changed_when: false
  become: false
  register: whoami

- name: Config | Set login_user with current user with username
  set_fact:
    login_user: "{{ whoami.stdout }}"

- name: Config | Add docker group
  group:
    name: docker
    state: present

- name: Config | Assign current user as docker group
  user:
    name: "{{ login_user }}"
    groups: docker
    append: true
    state: present

- name: Check | Check for nvme mountpoint exist
  stat:
    path: /mnt/nvme
  register: nvmemount

- name: Config | Make container storage path
  file:
    name: /mnt/nvme/docker
    state: directory
  when: nvmemount.stat.exists == True

- name: Config | Update dockerd configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  when: nvmemount.stat.exists == True

- name: Config | Update dockerd configuration
  copy:
    src: daemon_without_dataroot.json
    dest: /etc/docker/daemon.json
  when: nvmemount.stat.exists == False

- name: Config | Create systemd cgroup folder
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Control | Restart docker daemon
  systemd:
    name: docker
    state: restarted

